[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
via-ir = true
ffi = true
ast = true
extra_output = ["storageLayout"]
auto_detect_solc = true
gas_limit = "18446744073709551615"
